### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/compare-sprite-methods#1]
Hey, is there a plan for developing this further?

**Comment by w0rm** [comment]
@LappleApple nope, the only purpose of this was to share the code for the blogpost  https://tech.zalando.com/blog/creating-bulletproof-svg-icons/

I can move this to my personal github if you want

**Comment by lasomethingsomething** [comment]
Yeah, that seems like a good idea. Thanks!

**Comment by w0rm** [comment]
@LappleApple done
